### PR TITLE
Fix config.json issues

### LINKED ISSUE #1095: config.MpqLoadOrder is different for MacOS
**Describe the bug**

There is no official available Mac (darwin) version of Diablo 2. 

* https://eu.shop.battle.net/en-gb/product/diablo-ii
* https://eu.shop.battle.net/en-gb/product/diablo-ii-lord-of-destruction

So, MacOS developers, need to buy the game Windows PC version from Blizzard and then copy the MPQ files over to your Macbook. As a result the `config.json` should be the same with the one generated for Linux and Windows. But it's different, so the developer has to manually edit the file to make it look exactly the same as if they were building this project on a Windows box.

**To Reproduce**
1. Build the project on Mac system.
2. Notice the contents of the `config.json`.
3. Build the project on a Windows system.
4. Notice the contents of `config.json` are different from the Mac version.

How it is:

```
$ cat ~/Library/Application\ Support/OpenDiablo2/config.json
{
  "MpqLoadOrder": [
    "Diablo II Patch",
    "Diablo II Expansion Data",
    "Diablo II Expansion Movies",
    "Diablo II Expansion Music",
    "Diablo II Expansion Speech",
    "Diablo II Game Data",
    "Diablo II Graphics",
    "Diablo II Movies",
    "Diablo II Music",
    "Diablo II Sounds",
    "Diablo II Speech"
  ],
  "MpqPath": "/Applications/Diablo II/",
  "TicksPerSecond": -1,
  "FpsCap": 0,
  "SfxVolume": 1,
  "BgmVolume": 0.3,
  "FullScreen": false,
  "RunInBackground": true,
  "VsyncEnabled": true,
  "Backend": "Ebiten"
}
````

**Expected behavior**

```
{
  "MpqLoadOrder": [
    "patch_d2.mpq",
    "d2exp.mpq",
    "d2xmusic.mpq",
    "d2xtalk.mpq",
    "d2xvideo.mpq",
    "d2data.mpq",
    "d2char.mpq",
    "d2music.mpq",
    "d2sfx.mpq",
    "d2video.mpq",
    "d2speech.mpq"
  ],
  "MpqPath": "/Applications/Diablo II/",
  "TicksPerSecond": -1,
  "FpsCap": 0,
  "SfxVolume": 1,
  "BgmVolume": 0.3,
  "FullScreen": false,
  "RunInBackground": true,
  "VsyncEnabled": true,
  "Backend": "Ebiten"
}
```

**Desktop:**
 - OS: [macOS]
 - Version [Big Sur 11.2.3]

### LINKED ISSUE #1096: ConfigPath is not initialized if MPQ error occurs
**Describe the bug**

The `a.config.Path()` location not initialised properly. In case the file **already exists** and **there is an error** (e.g. missing MPQ files) then the `fmtErrSourceNotFound` error gets printed, but the file location is missing. This is because the `config` gets initialised via `json.NewDecoder(configAsset).Decode(config)` which is reading the file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change the `config.json` to point into wrong filepaths for MPQs.
2. Run the project.

### Actual Behaviour

**Logs**

```bash
$ go run main.go     
[App][INFO] loaded configuration file from    <----- SEE HERE IT'S MISSING
```

**Window**

bug

### Expected behaviour

It should point you to the actual file location, so the user knows which file to modify/edit accordingly.

**Logs**

```
[App][INFO] loaded configuration file from /Users/drpaneas/Library/Application Support/OpenDiablo2/config.json
```

**Window**

Fixed

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [Big Sur 11.2.3]

### PR DESCRIPTION
**Pull request by drpaneas**
Hello, this is my first contribution to the project. This PR is addressing the following two issues

Fixes #1096
Fixes #1095 

You can find more information on the relevant tickets.

### CODE REVIEW

File: d2core/d2config/defaults.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ func DefaultConfig() *Configuration {
 		MpqPath:         "C:/Program Files (x86)/Diablo II",
 		Backend:         "Ebiten",
 		MpqLoadOrder: []string{
-			"Patch_D2.mpq",
+			"patch_d2.mpq",
```
Comment (gucio321) [inline d2core/d2config/defaults.go:26]: thanx for changing it!

**Review by gucio321 — APPROVED** [review]

**Comment by gucio321** [comment]
also fixes #1095

**Comment by gucio321** [comment]
> Fixes #1096 #1095
FYI, this applies only for #1096, so you need to link this PR to #1095 too

**Review by essial — APPROVED** [review]
