### PR TITLE
fix(escape_menu): fix pentagrams starting position, fix #460

### LINKED ISSUE #460: Pentagrams position in the ingame escape menu
**Describe the bug**
When opening the escape menu ingame, the pentagrams are not correctly positioned.

**To Reproduce**
Start a new single player game. Press Escape.
=> The pentagrams appear above the menu.

Click on "OPTIONS"
=> The pentagrams appear above the menu.

=> It basically happens every time a new escape menu layout is loaded.

**Expected behavior**
The pentagrams should:
* Either surround the label hovered by the mouse cursor, if the mouse is hovering an element
* Either surround the topmost label

**Screenshots**
Normal menu:
image

With debug mode active (description below about how to activate it):
image

When opening a different layout:
image

**Additional context**
* It seems to be due to how the `d2gui` pkg works internally (elements position calculation VS rendering). We should someone find a way to calculate the elements positions BEFORE rendering them.
* The debug mode can be activated by going to `d2core/d2gui/layout.go` and uncommenting `if err := l.renderEntryDebug(entry, target); err != nil {`
* Code can be found in `d2game/d2gamescreen/escape_menu.go`
* Pentagrams should only surround `actionableElement` elements and not other regular labels like a title.

### PR DESCRIPTION
**Pull request by Benzhaomin**
default menu entry, and rotation direction

feels a bit hackish but it solves the issue right where it is, with no side effect

### CODE REVIEW

File: d2game/d2player/escape_menu.go [hunk 1]
```diff
@@ -360,6 +362,7 @@ func (m *EscapeMenu) OnLoad() {
 }
 
 func (m *EscapeMenu) OnEscKey() {
+	// note: original D2 returns straight to the game from however deep in the menu we are
```
Comment (joshjordan) [inline d2game/d2player/escape_menu.go:365]: Good catch. I ported this behavior over to `OnEscKey` without noticing this. Want to assign me an issue to fix?
