### PR TITLE
de-normalize file name before searching in MPQ

### LINKED ISSUE #86: error when first running OpenDiablo2: File '/data/global/sfx/cursor/button.wav' not found during preload of listfiles, and could not be located in any MPQ checking manually.
**Describe the bug**
OpenDiablo2 fails to locate the `/data/global/sfx/cursor/button.wav` sound effects resource when run on Linux. The resource is however present in the `d2sfx.mpq` archive.

**To Reproduce**
1. At rev c84698400b74c91518aa85afe4f1f21dac5ceb1f of OpenDiablo2.
2. Use config as listed below.
3. Run the OpenDiablo2 game on Linux.
4. Notice error mentioning `/data/global/sfx/cursor/button.wav` as reported to terminal.

```
$ OpenDiablo2
2019/11/05 22:52:22.877441 /home/u/Desktop/OpenDiablo2/main.go:27: OpenDiablo2 - Open source Diablo 2 engine
2019/11/05 22:52:22.882323 /home/u/Desktop/OpenDiablo2/Core/Engine.go:89: Loading configuration file
2019/11/05 22:52:22.882466 /home/u/Desktop/OpenDiablo2/Core/Engine.go:117: mapping mpq file structure
2019/11/05 22:52:23.424733 /home/u/Desktop/OpenDiablo2/Common/Palette.go:48: Loaded 18 palettes
2019/11/05 22:52:23.497935 /home/u/Desktop/OpenDiablo2/Common/TextDictionary.go:35: Loaded 9094 entries from the string table
2019/11/05 22:52:23.502664 /home/u/Desktop/OpenDiablo2/Common/LevelTypes.go:50: Loaded 38 LevelType records
2019/11/05 22:52:23.512479 /home/u/Desktop/OpenDiablo2/Common/LevelPresets.go:88: Loaded 1091 level presets
2019/11/05 22:52:23.537079 /home/u/Desktop/OpenDiablo2/Common/LevelWarp.go:48: Loaded 83 level warps
2019/11/05 22:52:23.560858 /home/u/Desktop/OpenDiablo2/Common/ObjectTypes.go:30: Loaded 573 object types
2019/11/05 22:52:23.569161 /home/u/Desktop/OpenDiablo2/Common/Objects.go:352: Loaded 571 objects
2019/11/05 22:52:23.579404 /home/u/Desktop/OpenDiablo2/Common/Weapons.go:281: Loaded 307 weapons
2019/11/05 22:52:23.590434 /home/u/Desktop/OpenDiablo2/Common/Missiles.go:304: Loaded 684 missiles
2019/11/05 22:52:23.611917 /home/u/Desktop/OpenDiablo2/Common/Sounds.go:97: Loaded 4699 sound definitions
2019/11/05 22:52:23.683136 /home/u/Desktop/OpenDiablo2/Core/Engine.go:207: File '/data/global/sfx/cursor/button.wav' not found during preload of listfiles, and could not be located in any MPQ checking manually.
```

**Expected behavior**
OpenDiablo2 would successfully locate the `button.wav` sound effect of `d2sfx.mpq`.

**Desktop (please complete the following information):**
 - Arch Linux

**Additional information:**

Contents of `config.json`:

```json
{
    "Language": "ENG",
    "FullScreen": true,
    "Scale": 1,
    "TicksPerSecond": -1,
    "RunInBackground": true,
    "VsyncEnabled": true,
    "SfxVolume": 1.0,
    "BgmVolume": 0.3,
    "MpqPath": "/home/u/_share_/diablo_ii/",
    "MpqLoadOrder": [
        "Patch_D2.mpq",
        "d2exp.mpq",
        "d2xmusic.mpq",
        "d2xtalk.mpq",
        "d2xvideo.mpq",
        "d2data.mpq",
        "d2char.mpq",
        "d2music.mpq",
        "d2sfx.mpq",
        "d2video.mpq",
        "d2speech.mpq"
    ]
}
```

```bash
$ ls /home/u/_share_/diablo_ii/
  d2char.mpq    d2music.mpq     d2video.mpq     d2xvideo.mpq
  d2data.mpq    d2sfx.mpq       d2xmusic.mpq    Patch_D2.mpq
  d2exp.mpq     d2speech.mpq    d2xtalk.mpq  
```

The `button.wav` file is present in `d2sfx.mpq`, as seen below:

mpqeditor

### PR DESCRIPTION
**Pull request by mewmew**
This was actually fixed by @essial.

Fixes #86.

### CODE REVIEW

File: Core/Engine.go [hunk 1]
```diff
@@ -195,7 +195,7 @@ func (v *Engine) LoadFile(fileName string) []byte {
 			if err != nil {
 				continue
 			}
-			if !mpq.FileExists(fileName) {
+			if !mpq.FileExists(strings.ToLower(strings.ReplaceAll(strings.ReplaceAll(fileName, "/data", "data"), "/", `\`))) {
```
Comment (mewmew) [inline Core/Engine.go]: This is the line that fixes it. The rest was just changes made by `goimports`.
